server:
  port: 8080

ltzf:
  sdk:
    config:
      enabled: true
person:
  sdk:
    name: yangbo
    address: shandong
    age: 18
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml